# Generated by Django 5.2.10 on 2026-01-16 02:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_dateoption_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='participant',
            name='username',
        ),
        migrations.AddField(
            model_name='event',
            name='event_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.eventuser'),
        ),
        migrations.AddField(
            model_name='participant',
            name='event_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='event_user', to='events.eventuser'),
        ),
    ]
