# Generated by Django 5.2.10 on 2026-01-16 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventuser_remove_participant_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.eventuser'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='event_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_user', to='events.eventuser'),
        ),
    ]
