# Generated by Django 5.2.10 on 2026-01-16 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_event_user_alter_participant_event_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('event', 'event_user')},
        ),
    ]
