# Generated by Django 5.2.10 on 2026-05-25 09:00

from django.db import migrations, models


def set_creators_as_organizers(apps, schema_editor):
    Participant = apps.get_model('events', 'Participant')
    for p in Participant.objects.select_related('event').all():
        if str(p.event_user_id) == str(p.event.event_user_id):
            p.is_organizer = True
            p.save(update_fields=['is_organizer'])


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_organizer',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_creators_as_organizers, migrations.RunPython.noop),
    ]
