### Создание пользователя

POST http://127.0.0.1:8000/api/auth/login/ HTTP/1.1
content-type: application/json

{
  "username": "anton2009",
  "email": "anton2009@mail.ru"
}


### Создание события

POST http://127.0.0.1:8000/api/events/ HTTP/1.1
content-type: application/json

{
  "event_user": "79546be5-a5c6-46ae-ad80-7c5add7629ff",
  "title": "Какое-то крутое событиееее",
  "description": "Выбираем дату",
  "dates": ["2026-05-10", "2026-05-11"]
}

### Просмотр события id сюда айди

GET http://127.0.0.1:8000/api/events/ab85da9d-8be7-45e4-84d5-83b822fc8c9f/ HTTP/1.1
content-type: application/json

### Создание участника

POST http://127.0.0.1:8000/api/events/ae85dc0f-b949-4e2a-98ff-dc361764b7d5/participants/ HTTP/1.1
content-type: application/json

{
  "event_user": "79546be5-a5c6-46ae-ad80-7c5add7629ff"
}

### Получение участников

GET http://127.0.0.1:8000/api/events/ae85dc0f-b949-4e2a-98ff-dc361764b7d5/participants/ HTTP/1.1
content-type: application/json

### Создание голоса

POST http://127.0.0.1:8000/api/events/ae85dc0f-b949-4e2a-98ff-dc361764b7d5/votes/
content-type: application/json

{
  "participant": "11a1fffe-4608-4b85-989c-2f171d6b2173",
  "date_option": 1
}

### Создание сообщения в ивенте с id выше и созданым участником

POST  http://127.0.0.1:8000/api/events/ae85dc0f-b949-4e2a-98ff-dc361764b7d5/messages/ HTTP/1.1
content-type: application/json

{
  "participant": "11a1fffe-4608-4b85-989c-2f171d6b2173",
  "text":"Балаболю балоболю"
}

### Получение сообщений события
GET  http://127.0.0.1:8000/api/events/ae85dc0f-b949-4e2a-98ff-dc361764b7d5/messages/ HTTP/1.1
content-type: application/json

### Получение списка ивентов для юзера

GET http://127.0.0.1:8000/api/users/b794ddcc-6272-42d3-b26a-0e5a56468eff/events/ HTTP/1.1
Content-Type: application/json

###